### ISSUE TITLE
表のスタイル修正

### ISSUE THREAD

**Issue by Kuwamai** [VirtualSpaceProgram/VirtualSpaceProgram.github.io#14]
横に長かったり、改行でぐちゃぐちゃになったりしてる。スタイルを直すか、表以外の表記方法を考える。

**Comment by makjapan** [comment]
markdownのテーブルはレイアウトが難しいですね
asciidocにするとか？
うーん...

**Comment by Kuwamai** [comment]
AsciiDoc! 聞いたことはあるのですが書いたことないですね...。一応色んな人に編集してもらえるようにMarkdown以外はしんどいのかなと思ってます。ので、うまいことCSSでいいかんじになったりしないかなーと思ってます。CSSも全然書いたこと無いのですがｗ

**Comment by Kuwamai** [comment]
とりあえず見ることはできるので、やや優先度低めな議題ですね。

**Comment by Kuwamai** [comment]
表を使わなくなったのでこちらもcloseします
