### ISSUE TITLE
タグ機能実装

### ISSUE THREAD

**Issue by Kuwamai** [VirtualSpaceProgram/VirtualSpaceProgram.github.io#15]
投稿をタグ別に分類する
http://jekyllrb-ja.github.io/docs/posts/

**Comment by Kuwamai** [comment]
タグ一覧
comic
magazine

**Comment by makjapan** [comment]
off-line （リアルイベント等）

**Comment by Kuwamai** [comment]
いいですねw

**Comment by Kuwamai** [comment]
こちらを参考にタグリストを実装しました。
[Jekyllサイトにシンプルなタグ・カテゴリのリストを実装 - Qiita](https://qiita.com/mnishiguchi/items/fa1e8fd2e893ea801ce8)
