### ISSUE TITLE
VSPイベントカレンダー

### ISSUE THREAD

**Issue by makjapan** [VirtualSpaceProgram/VirtualSpaceProgram.github.io#20]
今後の予定とか、まとめて表示したらいいのでは！

**Comment by makjapan** [comment]
2020年 VSPの今後のイベント

| 予定日時 | イベント | 案内人 |
|---|---|---|
| 4-19 21:00～ | 朝霧さんが語る！アニメーションライブ解説編&第6回雑談会 | S_朝霧 |
| 4-22 22:00～ | 電脳飲食店組合×VSPコラボ＠海の家「常夏」 | 天野テスラ |
| 4-29 22:00～ | 電脳飲食店組合×VSPコラボ＠しーわんカフェ | 天野テスラ |
| 5-05 22:00～ | 電脳飲食店組合×VSPコラボ＠大正浪漫カフェ | つらら | 
| 5-09 22:00～ | 電脳飲食店組合×VSPコラボ＠Bar.零凛 | 天野テスラ |
| 5-xx hh:mm～ | 第7回宇宙ガイド「天体写真編」 |  |

**Comment by Kuwamai** [comment]
2beb7b19c5cacebfa016c2a14c42d74f0d381946
なんかそれっぽくなりました

**Comment by Kuwamai** [comment]
イベントアーカイブに登録されたイベントのうち、日付が未来のものが今後開催予定のイベントとして表示されるようになりました。
なので開催予定のいべんとも #5 で受け付けたいと思います。
