### ISSUE TITLE
イベントアーカイブページ

### ISSUE THREAD

**Issue by Kuwamai** [VirtualSpaceProgram/VirtualSpaceProgram.github.io#5]
いついつこんなことがあったよって残しときたい

**Comment by makjapan** [comment]
天野ステラさんがDiscordの「サーバーの説明」チャンネルに書いてくれた軌跡から転載

## 天文仮想研究所VSPの軌跡
| 日時 | イベント名 | 案内人 | 
|-----|-----|-----|
| 2019-10-14 21:00-22:30 | 第一回宇宙ガイド　ISS・探査船編 | ろれる。＆えんでばー |
| 2019-10-15 | Discord設置 | | 
| 2019-10-26 22:00- | 顔合わせ兼命名式・第一回雑談会 | | 
| 2019-11-03 21:00- | 第二回雑談会 | | 
| 2019-11-17 21:00-22:30 | 第二回宇宙ガイド　ロケット編 | えんでばー&medaka |
| 2019-11-22 21:00- | ロケット編おかわり | えんでばー&medaka |
| 2019-12-01 21:00-23:00 | 第三回雑談会 | |
| 2019-12-21 21:00-23:00 | 第三回宇宙ガイド　月の世界へ | 天野ステラ&海崎マノン |
| 2019-12-27 21:00-22:00 | 忘年会 | |
| 2020-01-06 21:00- | Quest限定ロケット解説①　| ろれる。|
| 2020-01-18 21:00- | 特別編　プラネタリアン視聴会　| 片道ランナー |
| 2020-01-19 21:00- | 第四回宇宙ガイド　SF映画編　| ろれる。&Nyamo&蒼真アヤ |
| 2020-01-26 21:00-22:00 | 第四回雑談会 | |
| 2020-01-29 21:00-22:30 | Quest限定ロケット解説②　| ろれる。 |
| 2020-02-05 21:00- | Quest限定ロケット解説③　| ろれる。 |
| 2020-02-09 21:00- | 第五回宇宙ガイド　日本の宇宙事情 | S_朝霧&片道ランナー |
| 2020-02-12 21:00- | Quest限定ロケット解説④ | ろれる。&えんでばー |
| 2020-02-16 21:00-23:00 | 宇宙ガイド　ロケット編リバイバル | えんでばー&medaka |
| 2020-02-19 21:00- | Quest限定ロケット解説⑤ | ろれる。|
| 2020-02-20 | リンドの夜探し#44 | えんでばー |
| 2020-02-29 | そのらじ#29 | ろれる。|
| 2020-03-06 22:00-| 第五回雑談会「ようこそ！はじめてのVSP雑談会」| |
| 2020-03-08 20:30-23:30 | グランドツアー | |
| 2020-03-15 22:00-23:00 | VSP×Bar羽休めコラボ | 天野ステラ |
| 2020-03-20 22:00-23:00 | VSPグランドツアー Questお代わりツアー | makjapan |

**Comment by Kuwamai** [comment]
とりあえず表を流し込みました :raised_hands: 
https://virtualspaceprogram.github.io/docs/event_archive.html

**Comment by makjapan** [comment]
2020年1月25日（土）に名古屋市内で開催された技術イベント「xR Tech Nagoya #9」において実施された共催イベント「アストネスVR体験会#5（名古屋）」でのVR体験コンテンツとして、天文仮想研究所のメンバーとVRChatで交流するイベントが開催されました。

https://astoness.connpass.com/event/163678/

**Comment by makjapan** [comment]
ホームページに流し込むときに、表内のスラッシュを全部カンマに直していただいたようで、ありがとうございます。お手数おかけしました。

**Comment by Kuwamai** [comment]
いえいえどういたしまして!

**Comment by Kuwamai** [comment]
アストネスVR体験会反映しました
ca9239ced90165e23fb90be7619319f40095ae21

**Comment by makjapan** [comment]
|日時|イベント名|案内人|
|---|---|---|
| 2020-04-13 21:00-23:10 | 4月定期集会 ソユーズロケットと発射台の解説 【YouTube 同時LIVE】 | Fukuma |

**Comment by makjapan** [comment]
4月定期集会に参加された鍵丸さんによるイベント写真
https://t.co/H83CwS4qio

**Comment by Kuwamai** [comment]
ちょっと遅くなっちゃったのですが書きました :raised_hands: 
180ae3f78e9f933fbef6e687bec0c29267ad05be

**Comment by Kuwamai** [comment]
ちょっと対応いつになっちゃうかわからないのですがイベントリストをただの表じゃなくて、Newsページみたいに独立したページを一覧表示したいと思ってます。で、各ページにツイートや配信動画を埋め込めたらなと思います。

ので、イベントに関するツイートや動画もこちらで募集したいと思います。ちなみに優先度低めなのでそんなに急いでいる募集ではないです。

**Comment by makjapan** [comment]
| 日時 | イベント名 | 案内人 |
|----|----|----|
| 2020-04-18 21:00-23:00 | 臨時集会：VSPグランドツアーのリバイバル解説「アポロ計画のトラブル（1号・13号）」  | えんでばー |

**Comment by Kuwamai** [comment]
5f0d137db647d2fed9506dfbf9ad1fcb127e4793
更新しました

**Comment by Kuwamai** [comment]
ページが増えてきたので更新リクエスト用のissueを作成しました
#24
