### ISSUE TITLE
VSPスクラップブック

### ISSUE THREAD

**Issue by makjapan** [VirtualSpaceProgram/VirtualSpaceProgram.github.io#8]
VSPのことを取り上げてくれた記事やサイトやマンガなどを保存しておきたい！
リーチャ隊長のマンガとか。

**Comment by Kuwamai** [comment]
そしたらここに掲載候補となるリンクをじゃんじゃん貼っていったら良さそうですね。

**Comment by makjapan** [comment]
月刊星ナビに投稿掲載されたVSP紹介コラムは永久保存版だと思います。
![月刊星ナビ2020年4月号「クリップボード」](https://cdn.discordapp.com/attachments/638342370756263946/685096555618893824/image0.jpg)

**Comment by makjapan** [comment]
【バーチャル探検紀行37】![-](https://pbs.twimg.com/media/ETTRZ5mUUAEuewx?format=jpg&name=900x900)

**Comment by Kuwamai** [comment]
ですねですね。でも、記事の写真をサイトに載せちゃうのは著作権的にグレーですかね。いついつの星ナビに掲載されましたってことだけ書くのは問題ない気がしますが。

**Comment by Kuwamai** [comment]
Twitterに投稿された画像は規約的には転載OKなはずですが、せっかくなんでTweet自体のリンクを載せたほうが良さそうです。確かTweetをサイトに埋め込むこともできますよね。ちょっと後で調べてみますが。

**Comment by Kuwamai** [comment]
なので一旦画像そのものよりはURLを貼っていただけると嬉しいです :raised_hands:

**Comment by makjapan** [comment]
画像を表示するのではなく、紹介文とURLの記載に改めました。

**Comment by makjapan** [comment]
【バーチャル探検紀行35】（リーチャ隊長）
グランドツアーでの出来事がマンガになりました。
https://twitter.com/rietzscha/status/1239126834840629250

**Comment by makjapan** [comment]
【バーチャル探検紀行26】（リーチャ隊長）
グランドツアーに向けた告知イベントでの出来事がマンガになりました。
https://twitter.com/rietzscha/status/1234780565863186432

**Comment by makjapan** [comment]
【VRChat漫画 #58】（zefutefu）
イベントでの出来事がマンガになりました。
https://twitter.com/zefutefu/status/1233688904043118592

**Comment by makjapan** [comment]
【VRCギャッツラジオ 深夜テンション Session19】
我らが宣伝部長ギャッツさんによるグランドツアーの告知映像です
（YouTubeのギャッツラジオチャンネルにはアーカイブが見つからなかったのでTwitterのリンクです）
https://twitter.com/Shishinokami777/status/1230150057556463621

**Comment by makjapan** [comment]
【VRCギャッツラジオ 深夜テンション Session19】
我らが宣伝部長ギャッツさんによるグランドツアーの告知映像第一弾です
（YouTubeのギャッツラジオチャンネルにはアーカイブが見つからなかったのでTwitterのリンクです）
https://twitter.com/Shishinokami777/status/1229819615909253120

**Comment by makjapan** [comment]
アニメーションライブ「Escape」の作者、朝霧さんが、ギャッツさんからインタビューを受けて製作した映像について語っている映像です。
https://twitter.com/Shishinokami777/status/1236666820779601923

**Comment by makjapan** [comment]
ニコニコ動画に収録されたVSPイベントの紹介映像です。
https://www.nicovideo.jp/tag/天文仮想研究所VSP宇宙ガイド

**Comment by makjapan** [comment]
2020年1月25日（土）に名古屋市内で開催された技術イベント「xR Tech Nagoya #9」において実施された共催イベント「アストネスVR体験会#5（名古屋）」でのVR体験コンテンツとして、天文仮想研究所のメンバーとVRChatで交流するイベントが開催されました。

https://astoness.connpass.com/event/163678/

**Comment by makjapan** [comment]
ろれるさんがグランドツアー直前にVSP設立の思いを綴られました。
https://note.com/roreru/n/n4a072fbc1108

**Comment by Kuwamai** [comment]
Newsページはこれに近い感じをイメージしてます。
https://kageki.hankyu.co.jp/news/index.html

**Comment by Kuwamai** [comment]
Jekyllのpost機能がちょうどよさそうです。
http://jekyllrb-ja.github.io/docs/posts/

**Comment by Kuwamai** [comment]
Newsページを作ってみました :raised_hands:

**Comment by Kuwamai** [comment]
と思ったら何かエラー出てますね・w

**Comment by Kuwamai** [comment]
普通にファイルの一部をアップロードし忘れてただけでした。

**Comment by makjapan** [comment]
[VSP紹介記事公開ページ](https://virtualspaceprogram.github.io/2020/03/01/roreru_note.html)、

1. 1行目がテーブルになっておらず、文字列全体にリンクがついている
2. 2行名のURLにリンクがない（`天文仮想研究所 VSP`と`バーチャルライフマガジン`の間に`|`があるのが原因？）

**Comment by Kuwamai** [comment]
あっほんとですね。修正しました。`|`のせいですね。

**Comment by Kuwamai** [comment]
ページが増えてきたので更新リクエスト用のissueを作成しました
#24
